sudo: required

services:
- docker

jobs:
  include:
    - stage: Lint
      name: "Lint source files"
      script:
        - sudo pip install --upgrade ansible-lint
        - ansible-lint tests/test.yml

    - stage: Test
      name: "Debian 9 Test"
      script:
      - bash tests/run.sh debian-9

    - name: "CentOS 7 Test"
      script:
      - bash tests/run.sh centos-7

    - name: "ArchLinux Test"
      script:
      - bash tests/run.sh archlinux

notifications:
 webhooks: https://galaxy.ansible.com/api/v1/notifications/
