---
- include: dependencies/{{ ansible_distribution | lower }}.yml
  tags:
    - install
    - deps
  when: ansible_local.wireguard is not defined

- name: Flush deps handler
  meta: flush_handlers

- name: Enable WireGuard kernel module
  modprobe:
    name: wireguard
    state: present
  register: wireguard_module_enabled
  until:  wireguard_module_enabled is succeeded
  retries: 10
  delay: 10
  failed_when: wireguard_module_enabled is failure
  when: ignore_modprobe is not defined or (not ignore_modprobe)
  tags:
    - wg-install

- import_tasks: assert.yml
  tags:
    - check
  when: test_mode is defined

- import_tasks: config.yml
  tags:
    - config
